name: New formula labeler
description: Label new PRs as 'new formula' if files are added in Formula dir
author: dawidd6
branding:
  icon: git-pull-request
  color: blue
inputs:
  github_token:
    description: Github token
    required: true
runs:
  using: docker
  image: Dockerfile
