name: Build bottles

on: workflow_dispatch
  #  pull_request:
  #  paths:
  #    - 'Formula/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: setup
        uses: Homebrew/actions/setup-homebrew@master
      - name: Build bottles
        env:
          ROOT_URL: https://github.com/dawidd6/homebrew-test/releases/download/bottles
        run: brew test-bot --only-formulae --verbose --root-url=$ROOT_URL
      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bottles
          path: '*.bottle.*'
