name: Build bottles

on:
  workflow_dispatch:
    inputs:
      formula:
        description: Formula name
        required: false
        default: test-formula-git-revision

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: setup
        uses: Homebrew/actions/setup-homebrew@master
      - name: Hack test-bot
        run: |
          brew tap homebrew/test-bot
          cd $(brew --repo homebrew/test-bot)
          git fetch https://github.com/dawidd6/homebrew-test-bot github-releases
          git checkout --force --prune FETCH_HEAD
      - name: Build bottles
        run: brew test-bot --only-formulae --verbose
      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bottles
          path: '*.bottle.*'
