name: Close Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Delete PR head branch
      uses: dawidd6/action-delete-branch@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        numbers: ${{github.event.pull_request.number}}
