name: Dispatch build bottle

on:
  workflow_dispatch:
    inputs:
      macos:
        description: macOS version
        required: true
      formula:
        description: Formula name
        required: true
      issue:
        description: Issue number, where comment on failure would be posted
        required: false
      upload:
        description: Whether to upload built bottles to Bintray or not
        required: false

jobs:
  bottle:
    runs-on: ubuntu-latest
    steps:
      - name: Event inputs
        run: echo ${{github.event.inputs}}

      - name: Upload
        if: github.event.inputs.upload
        run: echo upload

      - name: Post comment on failure
        if: github.event.inputs.issue
        run: echo issue
