name: On branch created

on:
  create:
    branches: "*"

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.ref != "pr-*"
    steps:
      - name: Create pull request
        run: |
          cat $GITHUB_EVENT_PATH
