name: On branch created

on:
  create:
    branches:
      - "*"
      - "!pr-*"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        run: |
          cat $GITHUB_EVENT_PATH
