name: On pull request closed

on:
  pull_request:
    types:
      - "closed"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Delete merge branch
        run: |
          cat $GITHUB_EVENT_PATH
