name: On push

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: with env
        run: echo $GITHUB_ACTIONS
      - name: without env
        run: GITHUB_ACTIONS= echo $GITHUB_ACTIONS
