name: On push

on:
  push:
    branches: master

jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Install neofetch
        env:
          HOMEBREW_COLOR: 1
        run: |
          brew install neofetch
