name: On push

on:
  push:
    branches: master

jobs:
  main:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-10.14
    runs-on: ${{ matrix.os }}
    container: linuxbrew/brew
    steps:
      - name: brew config
        env:
          HOMEBREW_COLOR: 1
        run: |
          brew config
