name: TEST

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'alias brew="apt"' >> ~/.profile
          echo 'alias brew="apt"' | sudo tee -a /etc/profile
      - run: alias
      - run: brew --version
