name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: ruby --version
      - run: brew ruby -e "puts RUBY_VERSION"
      - run: brew config
