name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test1
        run: echo

      - id: test2
        run: echo "::set-output name=key::value"

      - if: ${{steps.test1.outputs.key}}
        run: echo ${{steps.test1.outputs.key}}

      - if: ${{steps.test2.outputs.key}}
        run: echo ${{steps.test2.outputs.key}}
