name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        uses: iMichka/actions/wait-for-idle-runner@octokit
        with:
          github_token: ${{github.token}}
          runner_name: name
          repository_name: repo

      - run: |
          echo ${{steps.test.outputs.runner-found}}
          echo ${{steps.test.outputs.runner-idle}}
