name: Test

on: repository_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: brew ls
      - if: ${{failure()}}
        run: echo first
      - if: ${{failure()}}
        run: echo second
