name: Test

on:
  workflow_dispatch:
    inputs:
      test:
        description: Test
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo test
        if: github.event.inputs.test
