name: Test

on:
  push:
    branches:
      - master

jobs:
  cancel1:
    runs-on: ubuntu-16.04
    if: false
    steps:
      - run: gcc --version
      - run: which -a gcc
  cancel2:
    runs-on: ubuntu-18.04
    if: true
    steps:
      - run: gcc --version
      - run: which -a gcc
  notcancel:
    needs:
      - cancel1
      - cancel2
    runs-on: ubuntu-latest
    steps:
      - run: echo run
