name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_HEAD_REF
      - run: echo $GITHUB_BASE_REF
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_REPOSITORY_OWNER

