name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: whoami
      - run: cat ~/.docker/config.json
      - run: sudo /root/.docker/config.json
