name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd ..
          rmdir $GITHUB_WORKSPACE
          ln -s $(brew --repo homebrew/core) $GITHUB_WORKSPACE
      - run: git branch -a
      - run: git log -10
      - run: |
          git clean -ffdx
          git remote set-url origin https://github.com/Homebrew/homebrew-core
          git fetch --prune --force origin master
          git checkout --force origin/master
      - run: git log -3
