name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: docker
      - run: docker version
      - run: |
          mkdir ~/.docker
          echo '{' > ~/.docker/config.json
          echo '  "experimental": “enabled”' >> ~/.docker/config.json
          echo '}' >> ~/.docker/config.json
      - run: docker
      - run: docker version
      - run: docker buildx
