name: Label new formula PRs

on:
  pull_request:
    types:
      - opened
    paths:
      - 'Formula/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
