name: Wheezy CI
on:
  push:
    branches:
      - master
jobs:
  wheezy_tests:
    runs-on: ubuntu-latest
    env:
      HOMEBREW_CORE_GIT_REMOTE: ${{github.event.repository.html_url}}
      HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1
    steps:
      - name: Run Docker
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_DEVELOPER: 1
          HOMEBREW_ON_DEBIAN7: 1
          HOMEBREW_CURL_PATH: "/usr/bin/curl"
          HOMEBREW_GIT_PATH: "/usr/bin/git"
        run: |
          docker run --env-file <(env | grep 'HOMEBREW\|GITHUB') homebrew/debian7:latest bash -c 'brew update-reset && brew config'
