name: ${{github.event.inputs.test}}

on:
  workflow_dispatch:
    inputs:
      test:
        description: desc
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
