on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v1
      - run: |
          docker build --platform=local -o . git://github.com/docker/buildx
          mkdir -p ~/.docker/cli-plugins && mv buildx ~/.docker/cli-plugins/docker-buildx
          #docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
      - run: |
          docker buildx create --use --name builder
      - run: |
          docker buildx inspect --bootstrap builder
      - run: |
          docker buildx build -t --platform=linux/amd64,linux/arm64 ruby-octokit .
