name: Close Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v2
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
