name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: which -a svn
      - run: svn --version
      - run: /usr/bin/svn --version
      - run: brew ls
      - run: ls -lh /usr/bin/svn
      - run: brew ruby -e "p Utils.svn_available?"
