name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        uses: GauthamGoli/actions/dispatch-build-bottle@dispatch-build-bottle-composite
        with:
          formula: hello
          issue: 0
          sender: me
