name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: ln -sT $(brew --repo homebrew/core) $GITHUB_WORKSPACE
      - run: ls
      - run: git log -3
      - run: |
          git clean -ffdx
          git remote set-url origin https://github.com/Homebrew/homebrew-core
          git fetch --prune --force origin master
          git checkout --force origin/master
      - run: git log -3
