name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest
    container:
      image: homebrew/brew
    steps:
      - run: gcc --version
      - run: which -a gcc
