on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker
    steps:
      - uses: actions/checkout@v1
      - run: |
          wget -O /usr/bin/buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
          chmod +x /usr/bin/buildx
      - run: docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
      - run: buildx create --use --name builder
      - run: buildx inspect --bootstrap builder
      - run: buildx build --platform=linux/amd64,linux/arm64,linux/arm -t ruby-octokit .
