name: Test

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: tag
        run: |
          echo "::set-output name=tag::${GITHUB_REF##*/}"
      - run: echo ${{steps.tag.outputs.tag}}
