name: Test

on:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          JSON='{"key":"val"}'
          echo "::set-output name=json::$JSON"
        id: json
      - run: |
          echo ${{steps.json.outputs.json}}
          echo ${{steps.json.outputs.json.key}}
 
