name: TEST

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - 
    steps:
      - run: uname
