name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Homebrew/actions/git-user-config@master
      - run: |
          touch file
          git checkout -b test
          git add file
          git commit -m file
          git checkout -
          git push origin test:test
