on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v1
      - run: |
          mkdir -p ~/.docker/cli-plugins
          docker build --platform=local -o ~/.docker/cli-plugins/docker-buildx git://github.com/docker/buildx
          #docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
          docker buildx create --use --name builder
          docker buildx inspect --bootstrap builder
          docker buildx build -t ruby-octokit .
