name: TEST

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          shopt -s expand_aliases
          alias brew="apt"
      - run: alias
        working-directory: bottles
      - run: brew --version
