name: Upload bottles

on:
  pull_request:
    types:
      - closed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Download
        uses: actions/download-artifact@v1
        with:
          name: bottle-${{github.event.pull_request.number}}
          path: ./
      - name: Print
        run: |
          cat $GITHUB_EVENT_PATH
          ls -R
          ls -R
          ls -R
